import { CreateCarData } from '../models/create-car-data'

export const carsDummyData: CreateCarData[] = [
  { name: 'Tesla Model 3', color: '#00FF00' },
  { name: 'Ford Focus', color: '#FF0000' },
  { name: 'Honda Civic', color: '#0000FF' },
  { name: 'Chevrolet Corvette', color: '#FFFF00' },
  { name: 'BMW M4', color: '#FF00FF' },
  { name: 'Audi A4', color: '#00FFFF' },
  { name: 'Toyota Camry', color: '#000000' },
  { name: 'Nissan Altima', color: '#800000' },
  { name: 'Jeep Wrangler', color: '#008000' },
  { name: 'Lexus RX', color: '#000080' },
  { name: 'Mercedes-Benz S-Class', color: '#808080' },
  { name: 'Volkswagen Golf', color: '#800080' },
  { name: 'Subaru Outback', color: '#008080' },
  { name: 'Porsche 911', color: '#FFA500' },
  { name: 'Mazda MX-5 Miata', color: '#FF4500' },
  { name: 'Kia Sportage', color: '#2E8B57' },
  { name: 'Volvo XC90', color: '#6A5ACD' },
  { name: 'Hyundai Tucson', color: '#FF69B4' },
  { name: 'Chrysler Pacifica', color: '#ADFF2F' },
  { name: 'Acura NSX', color: '#FFD700' },
  { name: 'Lamborghini Huracan', color: '#DA70D6' },
  { name: 'Ford Mustang', color: '#B0E0E6' },
  { name: 'Chevrolet Camaro', color: '#FF6347' },
  { name: 'Dodge Charger', color: '#40E0D0' },
  { name: 'Volkswagen Beetle', color: '#FFC0CB' },

  { name: 'Toyota Corolla', color: '#FF0000' },
  { name: 'Honda Accord', color: '#00FF00' },
  { name: 'Ford Explorer', color: '#0000FF' },
  { name: 'Chevrolet Blackado', color: '#FFFF00' },
  { name: 'BMW X5', color: '#FF00FF' },
  { name: 'Audi Q7', color: '#00FFFF' },
  { name: 'Nissan Rogue', color: '#000000' },
  { name: 'Jeep Grand Cherokee', color: '#800000' },
  { name: 'Hyundai Sonata', color: '#008000' },
  { name: 'Lexus ES', color: '#000080' },
  { name: 'Mercedes-Benz GLE', color: '#808080' },
  { name: 'Volkswagen Tiguan', color: '#800080' },
  { name: 'Subaru Forester', color: '#008080' },
  { name: 'Porsche Cayenne', color: '#FFA500' },
  { name: 'Mazda CX-5', color: '#FF4500' },
  { name: 'Kia Sorento', color: '#2E8B57' },
  { name: 'Volvo XC60', color: '#6A5ACD' },
  { name: 'Acura RDX', color: '#FF69B4' },
  { name: 'Chrysler 300', color: '#ADFF2F' },
  { name: 'Lamborghini Urus', color: '#FFD700' },
  { name: 'Ferrari 488', color: '#DA70D6' },
  { name: 'GMC Sierra', color: '#B0E0E6' },
  { name: 'Dodge Challenger', color: '#FF6347' },
  { name: 'Toyota RAV4', color: '#40E0D0' },
  { name: 'Volkswagen Passat', color: '#FFC0CB' },

  { name: 'Ford Fusion', color: '#FF0000' },
  { name: 'Honda CR-V', color: '#00FF00' },
  { name: 'Toyota Camry', color: '#0000FF' },
  { name: 'Chevrolet Equinox', color: '#FFFF00' },
  { name: 'BMW 3 Series', color: '#FF00FF' },
  { name: 'Audi A6', color: '#00FFFF' },
  { name: 'Nissan Sentra', color: '#000000' },
  { name: 'Jeep Compass', color: '#800000' },
  { name: 'Hyundai Elantra', color: '#008000' },
  { name: 'Lexus RX', color: '#000080' },
  { name: 'Mercedes-Benz E-Class', color: '#808080' },
  { name: 'Volkswagen Jetta', color: '#800080' },
  { name: 'Subaru Outback', color: '#008080' },
  { name: 'Porsche Panamera', color: '#FFA500' },
  { name: 'Mazda CX-9', color: '#FF4500' },
  { name: 'Kia Optima', color: '#2E8B57' },
  { name: 'Volvo S60', color: '#6A5ACD' },
  { name: 'Acura MDX', color: '#FF69B4' },
  { name: 'Chrysler Pacifica', color: '#ADFF2F' },
  { name: 'Lamborghini Aventador', color: '#FFD700' },
  { name: 'Ferrari 812 Superfast', color: '#DA70D6' },
  { name: 'GMC Yukon', color: '#B0E0E6' },
  { name: 'Dodge Durango', color: '#FF6347' },
  { name: 'Toyota Highlander', color: '#40E0D0' },
  { name: 'Volkswagen Atlas', color: '#FFC0CB' },

  { name: 'Chevrolet Malibu', color: '#FF0000' },
  { name: 'Toyota Prius', color: '#00FF00' },
  { name: 'Ford Escape', color: '#0000FF' },
  { name: 'Honda Pilot', color: '#FFFF00' },
  { name: 'BMW X3', color: '#FF00FF' },
  { name: 'Audi Q5', color: '#00FFFF' },
  { name: 'Nissan Maxima', color: '#000000' },
  { name: 'Jeep Renegade', color: '#800000' },
  { name: 'Hyundai Tucson', color: '#008000' },
  { name: 'Lexus NX', color: '#000080' },
  { name: 'Mercedes-Benz GLE', color: '#808080' },
  { name: 'Volkswagen Golf GTI', color: '#800080' },
  { name: 'Subaru Impreza', color: '#008080' },
  { name: 'Porsche Macan', color: '#FFA500' },
  { name: 'Mazda CX-30', color: '#FF4500' },
  { name: 'Kia Soul', color: '#2E8B57' },
  { name: 'Volvo XC40', color: '#6A5ACD' },
  { name: 'Acura TLX', color: '#FF69B4' },
  { name: 'Chrysler 300', color: '#ADFF2F' },
  { name: 'Lamborghini Huracan', color: '#FFD700' },
  { name: 'GMC Acadia', color: '#B0E0E6' },
  { name: 'Ferrari F8 Tributo', color: '#DA70D6' },
  { name: 'Dodge Journey', color: '#FF6347' },
  { name: 'Toyota 4Runner', color: '#40E0D0' },
  { name: 'Volkswagen Tiguan', color: '#FFC0CB' },
]
